import React from 'react'
import './Dashboard.css'

const AdminDashboard = () => {
  return (
    <div className="dashboard-container">
      <h2 className="dashboard-title">Admin Dashboard</h2>

      <div className="dashboard-section">
        <h3 className="section-heading">System Overview</h3>
        <div className="card">
          <p>Total Inventory: 120 items</p>
          <p>Users: 5 Admins, 20 Staff</p>
        </div>
      </div>

      <div className="dashboard-section">
        <h3 className="section-heading">Recent Activities</h3>
        <div className="card">
          <ul>
            <li>Inventory updated by Staff A</li>
            <li>Report generated by Admin B</li>
          </ul>
        </div>
      </div>

      <button className="logout-btn">Logout</button>
    </div>
  )
}

export default AdminDashboard
